### ISSUE TITLE
failed to lock vertex buffer in CMeshDX8:LockVertexBuffer

### ISSUE THREAD

**Issue by Manic-06** [crazyslavmodder/CSGO-MW2019-Weapons#1]
when i try to launch the game with everything installed i allways get this message, any fixes?

**Comment by crazyslavmodder** [comment]
It's an issue on CS:GO's end: installing too many weapons can easily crash your PC due to exceeding RAM usage. Try disabling some weapon addons to ease the load.

**Comment by Manic-06** [comment]
thanks it worked
